# Generated by Django 5.0.4 on 2024-04-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='sendmoney.country')),
                ('sender_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='sendmoney.country')),
            ],
        ),
    ]
