# Generated by Django 5.0.4 on 2024-04-24 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmoney', '0002_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='email',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
