# Generated by Django 5.0.4 on 2024-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmoney', '0003_rename_name_testimonial_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
