# Generated by Django 5.0.4 on 2024-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmoney', '0004_remove_transaction_receiver_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
